# Local Profile Overrides for Development and Debugging

# Datasource configuration for local environment
spring.datasource.url=jdbc:postgresql://localhost:5432/orders?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd

# Verbose SQL Logging and Formatting for Development
spring.jpa.properties.hibernate.format_sql=true
logging.level.orders.orders=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
