spring.application.name=orders

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensures Flyway is enabled
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Prevents accidental execution against a production DB if migrations are missing
spring.flyway.fail-on-missing-locations=true
# Clean is dangerous in production; disable it to prevent accidental data wipes
spring.flyway.clean-disabled=true

