### find all users
GET http://localhost:8080/api/v1/users
Content-Type: application/json


### create user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "mmahdy",
  "email": "mmahdy@test.com",
  "password": "P@ssw0rd",
  "enabled": true
}
