CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;
SELECT setval('users_seq', COALESCE((SELECT MAX(id) FROM users), 0) + 1);

CREATE SEQUENCE IF NOT EXISTS orders_seq START WITH 1 INCREMENT BY 50;
SELECT setval('orders_seq', COALESCE((SELECT MAX(id) FROM orders), 0) + 1);
