
CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_date   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    order_status VARCHAR(255),
    notes        VARCHAR(255),
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);